[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/eawsy/aws-lambda-go-core"

[[constraint]]
  branch = "master"
  name = "github.com/eawsy/aws-lambda-go-event"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/yunspace/serverless-golang"
